name: test build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v6
      - name: setup jdk
        uses: actions/setup-java@v5.0.0
      - name: build with maven
        run: mvn -B package --file pom.xml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v6
      - name: setup jdk
        uses: actions/setup-java@v5.0.0
      - name: setup chrome browser
        uses: browser actions/setup-chrome@v2
        with:
          install-chromedriver: true
            
      - name: test with maven
        run: mvn clean test
            
          
